export default [
    { id: 1, name: 'naredlav1'},
    { id: 2, name: 'julakann1'},
    { id: 3, name: 'tadis1'},
    { id: 4, name: 'Venu Naredla'},
    { id: 5, name: 'naredlavenu'},
    { id: 6, name: 'sai sankar'},
    { id: 7, name: 'venugopal'},
    { id: 8, name: 'Moshe Plotkin'},
    { id: 9, name: 'krishna srikanth'},
    { id: 10, name: 'Nithin Reddy'},
    { id: 11, name: 'Saraswathi kurra'},
    { id: 12, name: 'Purna Chandra'},
    { id: 13, name: 'Sarath'},
    { id: 14, name: 'M Sarath'},
    { id: 15, name: 'Naredla Venugopal'},
    { id: 16, name: 'Sankar naidu'},
    { id: 17, name: 'sai harika'},
    { id: 18, name: 'harika tadi'},
    { id: 19, name: 'Madhu Rao'},
    { id: 20, name: 'Naredla Uma'},
    { id: 21, name: 'barath'},
    { id: 22, name: 'satya'},
    { id: 23, name: 'harikasai'},
    { id: 24, name: 'Hanu'},
    { id: 25, name: 'Devi'}
];